### ISSUE TITLE
The Maybe

### ISSUE THREAD

**Issue by ammon0** [Hexworks/mixite#45]
Could you provide documentation for the Maybe class. Specifically:
* Why does getSatelliteData() return a Maybe?
* What does it mean when the Maybe is empty?

**Comment by ammon0** [comment]
I think I just worked out that an empty Maybe means that SatelliteData was never written to that grid point.

**Comment by adam-arold** [comment]
Precisely. It is **very** similar to the `Optional` in Java.

**Comment by ammon0** [comment]
I suppose I was getting hung up on getSatelliteData returning something different than setSatelliteData. It's a little less intuitive but I'll buy it. 

I was also having trouble running the example mentioned in the README. The instructions say to build it from `Hexworks/mixite`, then I saw the link to where it's been moved to its own repo.

**Comment by adam-arold** [comment]
You can come up to our [Discord Server](https://discordapp.com/invite/PE3qFmF) to discuss this if you want to. I think it would be a bit easier to communicate.

**Comment by ammon0** [comment]
Thank you, I'll do that.
