### ISSUE TITLE
calculateRingFrom function always returns an empty set

### ISSUE THREAD

**Issue by Welcius** [Hexworks/mixite#55]
The calculateRingFrom function is not correct since the return set is never modified, so it's always empty.

Take a look at the implementation here:

https://github.com/Hexworks/mixite/blob/97cf0d0ccce96401318aaa5c4e474310b6cf38ac/mixite.core/core/src/main/kotlin/org/hexworks/mixite/core/internal/impl/HexagonalGridCalculatorImpl.kt

**Comment by Welcius** [comment]
Also, I think that there is a for loop missing as well, it should loop between neighborIndexes 0..5 (if you check, neighborIndex is never modified).

**Comment by adam-arold** [comment]
You're right. I'm not sure how it ended up this way (I don't remember) but I think that this is an incomplete implementation.
